version: "3.5"

services:
  grafana:
    container_name: grafana
    network_mode: "host"
    image: grafana/grafana:latest
    restart: always
    volumes:
      - grafana_data:/var/lib/grafana
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
  prometheus:
    container_name: prometheus
    network_mode: "host"
    image: prom/prometheus:latest
    restart: always
    volumes:
      - ./etc-prometheus:/etc/prometheus
      - prometheus_data:/prometheus
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
  loki:
    container_name: loki
    network_mode: "host"
    image: grafana/loki:latest
    restart: always
    volumes:
      - ./etc-loki:/etc/loki
      - loki_data:/loki
    command: -config.file=/etc/loki/loki-config.yml
volumes:
    prometheus_data: {}
    grafana_data: {}
    loki_data: {}
